title: Sixteen Quotes
email: demataschristianowork@gmail.com
description: a hobby project of a dev
author: Another dev
#url:               "localhost:4000"
url: "https://dev-intj.github.io/sixteenquotes/"
baseurl:

# Social Profiles
twitter_username: dev_intj
github_username: dev-intj

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
